# Generated by Django 2.2.2 on 2019-08-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='cont',
        ),
    ]
