# Generated by Django 2.2.2 on 2019-08-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190827_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cont',
            new_name='Contact',
        ),
    ]
